In [ ]:
print(f"Shape before dropping duplicates: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"Shape after dropping duplicates: {df.shape}")

Shape before dropping duplicates: (2071700, 6)
Shape after dropping duplicates: (1598099, 6)

In [ ]:
print("Number of nulls before dropping:\n", df.isnull().sum())

Number of nulls before dropping:
 date             0
state            0
district         0
pincode          0
demo_age_5_17    0
demo_age_17_     0
dtype: int64

In [ ]:
df.dropna(inplace=True)
print(f"Shape after dropping null rows: {df.shape}")

Shape after dropping null rows: (1598099, 6)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/final_demographic_merged.csv')

In [ ]:
display(df.head())

,date,state,district,pincode,demo_age_5_17,demo_age_17_
0,01-03-2025,Uttar Pradesh,Gorakhpur,273213,49,529
1,01-03-2025,Andhra Pradesh,Chittoor,517132,22,375
2,01-03-2025,Gujarat,Rajkot,360006,65,765
3,01-03-2025,Andhra Pradesh,Srikakulam,532484,24,314
4,01-03-2025,Rajasthan,Udaipur,313801,45,785

In [ ]:
df['state'] = df['state'].str.lower().str.strip()
print("Unique values in 'state' column after standardization:")
print(df['state'].unique()[:10])
print(f"Number of unique states: {len(df['state'].unique())}")

Unique values in 'state' column after standardization:
['uttar pradesh' 'andhra pradesh' 'gujarat' 'rajasthan' 'karnataka'
 'west bengal' 'telangana' 'odisha' 'maharashtra' 'kerala']
Number of unique states: 58

In [ ]:
df['district'] = df['district'].str.lower().str.strip()
print("Unique values in 'district' column after standardization:")
print(df['district'].unique()[:10])
print(f"Number of unique districts: {len(df['district'].unique())}")

Unique values in 'district' column after standardization:
['gorakhpur' 'chittoor' 'rajkot' 'srikakulam' 'udaipur' 'sikar' 'tumakuru'
 'kurnool' 'paschim medinipur' 'ghazipur']
Number of unique districts: 961

In [ ]:
print("DataFrame Info:")
df.info()

print("\nFirst 10 unique values in 'state' column:")
print(df['state'].unique()[:10])

print("\nFirst 10 unique values in 'district' column:")
print(df['district'].unique()[:10])

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 1598099 entries, 0 to 2061699
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   date           1598099 non-null  datetime64[ns]
 1   state          1598099 non-null  object
 2   district       1598099 non-null  object
 3   pincode        1598099 non-null  int64
 4   demo_age_5_17  1598099 non-null  int64
 5   demo_age_17_   1598099 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 85.3+ MB

First 10 unique values in 'state' column:
['uttar pradesh' 'andhra pradesh' 'gujarat' 'rajasthan' 'karnataka'
 'west bengal' 'telangana' 'odisha' 'maharashtra' 'kerala']

First 10 unique values in 'district' column:
['gorakhpur' 'chittoor' 'rajkot' 'srikakulam' 'udaipur' 'sikar' 'tumakuru'
 'kurnool' 'paschim medinipur' 'ghazipur']

In [ ]:
state_mapping = {
    'new delhi': 'delhi'
}

df['state'] = df['state'].replace(state_mapping)
df['state'] = df['state'].str.replace('100000', '', regex=False).str.strip()

print("Unique values in 'state' column after further standardization:")
print(df['state'].unique()[:10])
print(f"Number of unique states: {len(df['state'].unique())}")

Unique values in 'state' column after further standardization:
['uttar pradesh' 'andhra pradesh' 'gujarat' 'rajasthan' 'karnataka'
 'west bengal' 'telangana' 'odisha' 'maharashtra' 'kerala']
Number of unique states: 58

In [ ]:
df['total_registrations'] = df['demo_age_5_17'] + df['demo_age_17_']

print("DataFrame head after creating 'total_registrations' column:")
display(df.head())

print("Unique values in 'state' column after all standardizations:")
print(df['state'].unique()[:10])
print(f"Number of unique states: {len(df['state'].unique())}")

DataFrame head after creating 'total_registrations' column:

,date,state,district,pincode,demo_age_5_17,demo_age_17_,total_registrations
0,2025-03-01,uttar pradesh,gorakhpur,273213,49,529,578
1,2025-03-01,andhra pradesh,chittoor,517132,22,375,397
2,2025-03-01,gujarat,rajkot,360006,65,765,830
3,2025-03-01,andhra pradesh,srikakulam,532484,24,314,338
4,2025-03-01,rajasthan,udaipur,313801,45,785,830

Unique values in 'state' column after all standardizations:
['uttar pradesh' 'andhra pradesh' 'gujarat' 'rajasthan' 'karnataka'
 'west bengal' 'telangana' 'odisha' 'maharashtra' 'kerala']
Number of unique states: 58

In [ ]:
print(f"Shape before removing '100000' from state: {df.shape}")
df = df[df['state'] != '100000']
print(f"Shape after removing '100000' from state: {df.shape}")

Shape before removing '100000' from state: (1598099, 7)
Shape after removing '100000' from state: (1598099, 7)

In [ ]:
print(f"Shape before removing empty string from state: {df.shape}")
df = df[df['state'] != '']
print(f"Shape after removing empty string from state: {df.shape}")

Shape before removing empty string from state: (1598099, 7)
Shape after removing empty string from state: (1598097, 7)

In [ ]:
print("Unique values and their counts in 'state' column after all cleaning:")
print(df['state'].value_counts())
print(f"Total number of unique states: {len(df['state'].unique())}")

Unique values and their counts in 'state' column after all cleaning:
state
andhra pradesh                              154790
tamil nadu                                  153333
uttar pradesh                               132366
maharashtra                                 126303
west bengal                                 124776
karnataka                                   120416
kerala                                       82186
gujarat                                      75161
bihar                                        74539
odisha                                       71767
telangana                                    70098
rajasthan                                    68455
madhya pradesh                               60157
assam                                        47408
punjab                                       38097
jharkhand                                    31245
chhattisgarh                                 27286
haryana                                      22341
himachal pradesh                             21940
uttarakhand                                  17710
jammu and kashmir                            15738
orissa                                       10731
delhi                                         8066
tripura                                       6968
manipur                                       5744
goa                                           4609
meghalaya                                     4180
arunachal pradesh                             3608
nagaland                                      3109
mizoram                                       3010
sikkim                                        2452
puducherry                                    2111
pondicherry                                   1699
chandigarh                                    1536
andaman and nicobar islands                    905
ladakh                                         672
lakshadweep                                    410
dadra and nagar haveli and daman and diu       407
andaman & nicobar islands                      384
daman and diu                                  319
jammu & kashmir                                277
dadra and nagar haveli                         252
daman & diu                                    200
west bangal                                     96
westbengal                                      93
dadra & nagar haveli                            72
west  bengal                                    61
uttaranchal                                      3
chhatisgarh                                      2
west bengli                                      2
darbhanga                                        1
puttenahalli                                     1
balanagar                                        1
jaipur                                           1
madanapalle                                      1
nagpur                                           1
raja annamalai puram                             1
Name: count, dtype: int64
Total number of unique states: 57

In [ ]:
state_corrections = {
    'orissa': 'odisha',
    'jammu & kashmir': 'jammu and kashmir',
    'andaman & nicobar islands': 'andaman and nicobar islands',
    'daman and diu': 'dadra and nagar haveli and daman and diu',
    'dadra and nagar haveli': 'dadra and nagar haveli and daman and diu',
    'daman & diu': 'dadra and nagar haveli and daman and diu',
    'dadra & nagar haveli': 'dadra and nagar haveli and daman and diu',
    'pondicherry': 'puducherry',
    'west bangal': 'west bengal',
    'westbengal': 'west bengal',
    'west  bengal': 'west bengal',
    'west bengli': 'west bengal',
    'chhatisgarh': 'chhattisgarh',
    'uttaranchal': 'uttarakhand'
}
df['state'] = df['state'].replace(state_corrections)

# Identify non-state names that should be removed
non_state_names = [
    'darbhanga',
    'puttenahalli',
    'balanagar',
    'jaipur',
    'madanapalle',
    'nagpur',
    'raja annamalai puram'
]

print(f"Shape before removing non-state names: {df.shape}")
df = df[~df['state'].isin(non_state_names)]
print(f"Shape after removing non-state names: {df.shape}")

print("Unique values and their counts in 'state' column after further cleaning:")
print(df['state'].value_counts())
print(f"Total number of unique states: {len(df['state'].unique())}")

Shape before removing non-state names: (1598097, 7)
Shape after removing non-state names: (1598090, 7)
Unique values and their counts in 'state' column after further cleaning:
state
andhra pradesh                              154790
tamil nadu                                  153333
uttar pradesh                               132366
maharashtra                                 126303
west bengal                                 125028
karnataka                                   120416
odisha                                       82498
kerala                                       82186
gujarat                                      75161
bihar                                        74539
telangana                                    70098
rajasthan                                    68455
madhya pradesh                               60157
assam                                        47408
punjab                                       38097
jharkhand                                    31245
chhattisgarh                                 27288
haryana                                      22341
himachal pradesh                             21940
uttarakhand                                  17713
jammu and kashmir                            16015
delhi                                         8066
tripura                                       6968
manipur                                       5744
goa                                           4609
meghalaya                                     4180
puducherry                                    3810
arunachal pradesh                             3608
nagaland                                      3109
mizoram                                       3010
sikkim                                        2452
chandigarh                                    1536
andaman and nicobar islands                   1289
dadra and nagar haveli and daman and diu      1250
ladakh                                         672
lakshadweep                                    410
Name: count, dtype: int64
Total number of unique states: 36

In [ ]:
# Normalize strings (lowercase and remove extra spaces)
df['state'] = df['state'].str.lower().str.strip()

# 2. Map old/duplicate names to official 2026 standards
mapping = {
    'orissa': 'odisha',
    'daman and diu': 'dadra and nagar haveli and daman and diu',
    'dadra and nagar haveli & daman and diu': 'dadra and nagar haveli and daman and diu'
}

df['state'] = df['state'].replace(mapping)

# 3. Verify the final count
unique_count = df['state'].nunique()
print(f"Total Unique Entities: {unique_count}")
print(df['state'].unique())

Total Unique Entities: 36
['uttar pradesh' 'andhra pradesh' 'gujarat' 'rajasthan' 'karnataka'
 'west bengal' 'telangana' 'odisha' 'maharashtra' 'kerala' 'bihar'
 'tamil nadu' 'madhya pradesh' 'assam' 'tripura' 'arunachal pradesh'
 'punjab' 'jharkhand' 'delhi' 'chandigarh' 'chhattisgarh'
 'jammu and kashmir' 'mizoram' 'nagaland' 'himachal pradesh' 'goa'
 'haryana' 'meghalaya' 'uttarakhand' 'manipur'
 'dadra and nagar haveli and daman and diu' 'puducherry' 'sikkim' 'ladakh'
 'andaman and nicobar islands' 'lakshadweep']

In [ ]:
adhaar_df.to_csv('adhaar_merged_cleaned.csv', index=False)
print("DataFrame saved to 'adhaar_merged_cleaned.csv'")

DataFrame saved to 'adhaar_merged_cleaned.csv'

In [ ]:
print("All unique states in adhaar_df:")
for state in adhaar_df['state'].unique():
    print(state)

All unique states in adhaar_df:
meghalaya
karnataka
uttar pradesh
bihar
maharashtra
haryana
rajasthan
punjab
delhi
madhya pradesh
west bengal
assam
uttarakhand
gujarat
andhra pradesh
tamil nadu
chhattisgarh
jharkhand
nagaland
manipur
telangana
tripura
mizoram
jammu and kashmir
chandigarh
sikkim
orissa
kerala
dadra and nagar haveli & daman and diu
arunachal pradesh
himachal pradesh
goa
ladakh
andaman and nicobar islands
puducherry
lakshadweep
daman and diu
odisha

In [ ]:
import pandas as pd

adhaar_df = pd.read_csv('/content/adhaar_enrollment_merged.csv')
print("Adhaar Enrollment DataFrame loaded. Displaying first 5 rows:")
display(adhaar_df.head())

Adhaar Enrollment DataFrame loaded. Displaying first 5 rows:

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,total_registrations
0,2025-03-02,meghalaya,east khasi hills,793121,11,61,37,109
1,2025-03-09,karnataka,bengaluru urban,560043,14,33,39,86
2,2025-03-09,uttar pradesh,kanpur nagar,208001,29,82,12,123
3,2025-03-09,uttar pradesh,aligarh,202133,62,29,15,106
4,2025-03-09,karnataka,bengaluru urban,560016,14,16,21,51

In [ ]:
print("Unique states in the adhaar_df DataFrame:")
print(f"Number of unique states: {len(adhaar_df['state'].unique())}")

Unique states in the adhaar_df DataFrame:
Number of unique states: 38

In [ ]:
df.to_csv('demographic_merged_cleaned.csv', index=False)
print("DataFrame saved to 'demographic_merged_cleaned.csv'")

DataFrame saved to 'demographic_merged_cleaned.csv'